baseURL = 'https://example.org/'
languageCode = 'es-mx'
title = 'Taller Lean 2024 - Git & GitHub Workshop'
canonifyURLs = true

[params]
# color style
color = 'light' # linen, wheat, gray, light

# header social icons
github = 'lambda-style/taller-verano-2024' # github.com/YOUR_GITHUB_ID
rss = true                                 # show rss icon

# home page profile
name = 'Taller Lean - Verano 2024'
bio = 'Directorio de asistentes del grupo de estudio de Lean, llevado a cabo durante el verano 2024 por estudiantes y académicos en la Facultad de Ciencias, UNAM.'


# misc
disableHLJS = true                # disable highlight.js
disablePostNavigation = true      # disable post navigation
monoDarkIcon = true               # show monochrome dark mode icon
gravatarCdn = 'GRAVATAR_CDN_LINK' # e.g. 'https://cdn.v2ex.com/gravatar/'
math = true                       # enable KaTeX math typesetting globally
localKatex = false                # use local KaTeX js/css instead of CDN
favicon = "favicon.ico"           # customize the default favicon

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"
disable = false
[[module.imports]]
path = 'github.com/hugomods/images'
